### ISSUE TITLE
As a returning resume maker, I want to be able to view all my resumes in one place so I could reference them at a later time.

### ISSUE THREAD

**Issue by iquitgame** [xlab-classes/Cse442-spring2022-HireMi#14]
**Acceptance Tests:**

*Test 1*

1) Pre-requisite, must have an account that has previously saved resumes.
2) Go to the website: https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442r/
3) Log in to your account using your google account.
4) Click on your account page from the menu and it should take you to your dashboard
5) You will be able to view all your past resumes

**Comment by AsifIftekhar2** [comment]
#20
