### ISSUE TITLE
As a registered account holder, I want to edit my relevant information in my account and UI so that I can customize my experience.

### ISSUE THREAD

**Issue by iquitgame** [xlab-classes/Cse442-spring2022-HireMi#16]
**Acceptance Tests:**

*Test 1*
1) Login with your UB account.
2) Click on the menu icon at the top of the page
3) Click on Settings
4) A page will appear with all the account settings and data for the user
5) Set the user name to John Doe (or Jane Doe if your real name is John Doe).
6) Verify that the name updates.
7) Change the profile picture.
8) Verify that the profile picture changes.

**Comment by AsifIftekhar2** [comment]
#28
