### ISSUE TITLE
Design resume dashboard page

### ISSUE THREAD

**Issue by AsifIftekhar2** [xlab-classes/Cse442-spring2022-HireMi#20]
**Task Tests**

*Test 1*
1. Open the designed pages for the site on Figma.
2. Navigate to the dashboard page design.
3. Ensure each text element is legible.
4. Ensure that a navigation object is available.
5. Ensure a feature to view multiple resumes is available.

**Comment by PotLid** [comment]
Currently working on it

**Comment by PotLid** [comment]
Done
